version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{- if .Arm }}_v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        formats: [zip]

release:
  footer: ""

changelog:
  use: github
